//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CPlot.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CPLOTTYPE                   129
#define IDS_tempstring                  129
#define ID_PLOTSETTINGS_COLORTABLE_BLACKANDWHITE 32771
#define ID_PLOTSETTINGS_COLORTABLE_RAINBOW 32772
#define ID_PLOTSETTINGS_COLORTABLE_REDTEMPERATURE 32773
#define ID_PLOTSETTINGS_COLORTABLE_16LEVEL 32774
#define ID_PLOTSETTINGS_COLORTABLE_BEACH 32775
#define ID_PLOTSETTINGS_COLORTABLE_BLUEPASTELRED 32776
#define ID_PLOTSETTINGS_COLORTABLE_BLUERED 32777
#define ID_PLOTSETTINGS_COLORTABLE_BLUEWAVES 32778
#define ID_PLOTSETTINGS_COLORTABLE_EOSA 32779
#define ID_PLOTSETTINGS_COLORTABLE_EOSB 32780
#define ID_PLOTSETTINGS_COLORTABLE_GREENPINK 32781
#define ID_PLOTSETTINGS_COLORTABLE_GREENREDBLUE 32782
#define ID_PLOTSETTINGS_COLORTABLE_HARDCANDY 32783
#define ID_PLOTSETTINGS_COLORTABLE_HAZE 32784
#define ID_PLOTSETTINGS_COLORTABLE_HSV1 32785
#define ID_PLOTSETTINGS_COLORTABLE_HSV2 32786
#define ID_PLOTSETTINGS_COLORTABLE_MACSTYLE 32787
#define ID_PLOTSETTINGS_COLORTABLE_NATURE 32788
#define ID_PLOTSETTINGS_COLORTABLE_OCEAN 32789
#define ID_PLOTSETTINGS_COLORTABLE_PASTEL 32790
#define ID_PLOTSETTINGS_COLORTABLE_PEPPERMINT 32791
#define ID_PLOTSETTINGS_COLORTABLE_PLASMA 32792
#define ID_PLOTSETTINGS_COLORTABLE_PRISM 32793
#define ID_PLOTSETTINGS_COLORTABLE_PURPLEREDSTRIPES 32794
#define ID_PLOTSETTINGS_COLORTABLE_RAINBOW18 32795
#define ID_PLOTSETTINGS_COLORTABLE_RAINBOWBLACK 32796
#define ID_PLOTSETTINGS_COLORTABLE_RAINBOWWHITE 32797
#define ID_PLOTSETTINGS_COLORTABLE_REDPURPLE 32798
#define ID_PLOTSETTINGS_COLORTABLE_STDGAMMAII 32799
#define ID_PLOTSETTINGS_COLORTABLE_STEPS 32800
#define ID_PLOTSETTINGS_COLORTABLE_STERNSPECIAL 32801
#define ID_PLOTSETTINGS_COLORTABLE_VOLCANO 32802
#define ID_PLOTSETTINGS_COLORTABLE_WAVES 32803
#define ID_CHART_XYCHART                32804
#define ID_CHART_2DCHART                32805
#define ID_PLOTSETTINGS_PLOTSETUP       32806
#define ID_PLOTSETTINGS_AXISSETUP       32807
#define ID_PLOTSETTINGS_DATASETUP       32808
#define ID_PLOTSETTINGS_COLORTABLE      32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
